## note: add site title for primer (default) theme to avoid duplicate titles getting (auto-) added
##   note: title must match the heading 1 in the readme
title: "Text with Instructions (.texti) - Structured Documents in Text with Formatting Conventions"

## add emoji support

plugins:
- jemoji

